emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-js"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@typespec/http-client-js":
    emitter-output-dir: "{output-dir}/sdk/javascript"
    package-details:
      name: "@siraluda/revisionweek-client"
      description: "This is a javascript/typescript client library for the RevisionWeek API"
      version: 1.0.0

output-dir: "{project-root}/dist"

linter:
  extends:
    - "@typespec/http/all"
